# ============================================================
# R/revision_2026/06_supp_window_check_revised.R
# ============================================================
# Appendix B rerun: the observation-window omitted-context check, redone
# under the REVISED slow-fast model (N=9, tau_i/omega_ij/gamma_i, the same
# logit-linear fast layer used in Simulations 1-4) instead of the
# pre-revision N=12 / h_i / static-joint-sampler design used by
# R/scripts/10_network_window_check.R. That old script's numbers (the
# gap 12.3 -> 10.8 -> 7.7 -> 3.9, edge deviation 0.132 -> 0.024 currently
# sitting in the manuscript's Appendix B) belong to a different model and
# should NOT be reused -- this script exists to replace them with numbers
# actually generated by the model the rest of the paper uses.
#
# Question: when the slow contextual field P_t is omitted from an
# estimated symptom network, does the resulting distortion depend on how
# much slow-context variation survives in the observation window used to
# form each person's covariate?
#
# Design
# ------
# Each simulated person's slow context follows the SAME mean-reverting OU
# process used in Simulations 2/3 (kappa, sigma_P, dt, P_base=0), with
# shocks and symptom-to-context feedback both off (b=0), so this is a
# pure background-fluctuation design, not a stress/recovery one. After a
# long burn-in (to reach OU stationarity), we average the process over a
# window of length W steps to get that person's observed covariate,
#   Pbar_i = (1/W) * sum_{t=1}^{W} P_i(t).
# A short window (W small relative to tau_P = 1/kappa) closely tracks the
# instantaneous slow state; a long window averages over more of the OU
# process's own fluctuation, which is exactly the "aggregation" a slow
# field is expected to wash out.
#
# The person's SYMPTOM profile is then generated exactly the way
# Simulation 4 generates a cross-sectional observation: starting from a
# random state, sweep the fast layer via simulate_fast_sweep() for T_burn
# steps CONDITIONAL ON Pbar_i (i.e., we treat the window-averaged slow
# field as the value symptoms actually equilibrate against over that
# same observation period -- the same "slow field an observer would
# measure and that shapes symptoms over that period" logic used
# throughout the paper), and keep the final state. This reuses
# simulate_fast_sweep() and fit_edges() from utils_uncentered01_model.R
# unchanged, so the estimator here is identical to Simulation 4's, not a
# separately-implemented copy.
#
# Between-person variance in Pbar_i comes ENTIRELY from the OU process's
# own stochastic fluctuation around the shared baseline P_base=0 (no
# fixed per-person offset, no between-group mu split) -- this mirrors
# 10_network_window_check.R's actual within-group logic (that script's
# apparent "sd_pbar" decrease with window length is driven purely by OU
# noise shrinking under time-averaging, not by any fixed heterogeneity
# term), so the same qualitative story should still be testable here: if
# sd(Pbar) does not fall appreciably across the window grid at a given
# sigma_P, the omitted-context gap should not be expected to fall either.
#
# We use two sigma_P conditions: "low" = 0.04, IDENTICAL to the
# background diffusion scale already used in Simulations 2/3 (so this
# condition is literally "the same slow field examined at different
# aggregation windows," not a new parameter regime), and "high" = 0.65,
# chosen only to make the window-length effect visually detectable (its
# stationary sd, sigma_P/sqrt(2*kappa), is ~1.03 -- comparable in scale
# to the P range already used in Simulation 1/4, -0.6 to 0.6). If the low
# condition shows a negligible effect (plausible, since Sim2/3's
# background diffusion is deliberately small), report that directly
# rather than dropping the condition -- a null result here is itself
# informative about how much this problem matters at the diffusion scale
# used elsewhere in the paper.
#
# IMPORTANT: unlike the old script, this design has only ONE true
# generating network (the same omega used throughout the paper), so there
# is no need to redraw a new data-generating network per replicate --
# n_reps below are Monte Carlo repeats of the same DGP for stable SEs,
# not redraws of the DGP itself.
#
# Outputs
# -------
#   res/revision_2026/window_check/window_check_raw.rds
#   res/revision_2026/window_check/window_check_summary.csv
#   figs/revision_2026/Figure_S_window_check_revised.pdf / .png
# ============================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(parallel)
})

source("R/revision_2026/utils_uncentered01_model.R")   # simulate_fast_sweep(), fit_edges()
source("R/revision_2026/00_parameters_uncentered01.R")  # tau (+1.3 shift), omega, gamma, symptoms, N

# ------------------------------------------------------------------------
# Slow-field OU parameters -- identical to Simulations 2/3 so tau_P has
# the same meaning as elsewhere in the paper.
# ------------------------------------------------------------------------
kappa   <- 0.20
dt      <- 0.02
P_base  <- 0
tau_P_steps <- 1 / (kappa * dt)   # = 250 steps, same interpretation as the old check

sigma_P_levels <- c(low = 0.04, high = 0.65)

burn_in_ou_steps <- round(4 * tau_P_steps)   # let P reach OU stationarity first
window_steps     <- c(1, 25, 100, 250, 500, 1000, 2500, 5000)  # W, in steps

T_burn_symptom <- 200L   # fast-layer burn-in per person, same as Sim 1 / Sim 4

n_person <- 2000L        # per (sigma_P, W) condition
n_reps   <- 5L            # Monte Carlo repeats of the same DGP, for SEs

iu <- which(upper.tri(matrix(0, N, N)))
true_omega_edges <- omega[iu]
true_gs <- sum(abs(true_omega_edges))

n_cores <- max(1, parallel::detectCores(logical = TRUE) - 1, na.rm = TRUE)
cat(sprintf("Using %d cores.\n", n_cores))
RNGkind("L'Ecuyer-CMRG")
set.seed(20260826)

# ------------------------------------------------------------------------
# Vectorized OU window-average: n_person independent people at once.
# Returns Pbar_i for each person (the observed, window-averaged covariate).
# ------------------------------------------------------------------------
simulate_ou_window_means <- function(sigma_P, n_ind, W_steps, burn_in) {
  P <- rep(P_base, n_ind)
  total_steps <- burn_in + W_steps
  running_sum <- numeric(n_ind)
  for (t in seq_len(total_steps)) {
    P <- P + kappa * (P_base - P) * dt + sigma_P * sqrt(dt) * rnorm(n_ind)
    if (t > burn_in) running_sum <- running_sum + P
  }
  running_sum / W_steps
}

# ------------------------------------------------------------------------
# One person's symptom snapshot: same logic as Simulation 4's
# simulate_person(), just conditioning on Pbar_i instead of a fixed/drawn P.
# ------------------------------------------------------------------------
simulate_person_given_Pbar <- function(Pbar) {
  S <- rbinom(N, size = 1, prob = 0.5)
  for (t in seq_len(T_burn_symptom)) {
    S <- simulate_fast_sweep(S, tau, omega, gamma, Pbar)
  }
  S
}

# ------------------------------------------------------------------------
# One (sigma_P, W, rep) condition: simulate Pbar for n_person people,
# generate their symptom profiles, fit symptom-only vs context-adjusted
# networks, and summarize.
# ------------------------------------------------------------------------
run_condition <- function(sigma_P_name, W_steps, rep) {
  sigma_P <- sigma_P_levels[[sigma_P_name]]
  seed <- 1e6 * which(names(sigma_P_levels) == sigma_P_name) + 1000 * rep + W_steps
  set.seed(seed)

  Pbar <- simulate_ou_window_means(sigma_P, n_person, W_steps, burn_in_ou_steps)

  rows <- parallel::mclapply(seq_len(n_person), function(i) simulate_person_given_Pbar(Pbar[i]),
                              mc.cores = n_cores, mc.set.seed = TRUE)
  failed <- vapply(rows, function(x) inherits(x, "try-error"), logical(1))
  if (any(failed)) stop(sprintf("%d of %d person-simulations failed.", sum(failed), n_person))
  S <- do.call(rbind, rows)

  omega_hat_naive    <- fit_edges(S, Pvec = NULL)
  omega_hat_adjusted <- fit_edges(S, Pvec = Pbar)

  tibble(
    sigma_P_level = sigma_P_name, sigma_P = sigma_P, W_steps = W_steps, rep = rep,
    sd_pbar = sd(Pbar),
    gs_naive = sum(abs(omega_hat_naive[iu])),
    gs_adjusted = sum(abs(omega_hat_adjusted[iu])),
    mae_naive_all = mean(abs(omega_hat_naive[iu] - true_omega_edges)),
    mae_adjusted_all = mean(abs(omega_hat_adjusted[iu] - true_omega_edges)),
    mae_naive_true_zero = mean(abs(omega_hat_naive[iu][true_omega_edges == 0])),
    mae_adjusted_true_zero = mean(abs(omega_hat_adjusted[iu][true_omega_edges == 0])),
    n_phantom_naive_gt_01 = sum(true_omega_edges == 0 & abs(omega_hat_naive[iu]) > 0.1),
    n_phantom_adjusted_gt_01 = sum(true_omega_edges == 0 & abs(omega_hat_adjusted[iu]) > 0.1)
  )
}

# ------------------------------------------------------------------------
# Run: 2 sigma_P levels x 8 window lengths x n_reps, sequential over
# conditions (each condition is already parallelized internally over
# n_person via mclapply above).
# ------------------------------------------------------------------------
design <- expand_grid(sigma_P_level = names(sigma_P_levels), W_steps = window_steps, rep = seq_len(n_reps))
cat(sprintf("Running %d conditions (%d sigma_P levels x %d window lengths x %d reps), n_person=%d each...\n",
            nrow(design), length(sigma_P_levels), length(window_steps), n_reps, n_person))

results <- design |>
  purrr::pmap_dfr(function(sigma_P_level, W_steps, rep) {
    cat(sprintf("  sigma_P=%s, W=%d, rep=%d\n", sigma_P_level, W_steps, rep))
    run_condition(sigma_P_level, W_steps, rep)
  })

dir.create("res/revision_2026/window_check", recursive = TRUE, showWarnings = FALSE)
dir.create("figs/revision_2026", recursive = TRUE, showWarnings = FALSE)

saveRDS(list(results = results,
             params = list(kappa = kappa, dt = dt, P_base = P_base,
                            sigma_P_levels = sigma_P_levels,
                            burn_in_ou_steps = burn_in_ou_steps,
                            window_steps = window_steps,
                            T_burn_symptom = T_burn_symptom,
                            n_person = n_person, n_reps = n_reps,
                            true_omega = omega, true_gs = true_gs)),
        "res/revision_2026/window_check/window_check_raw.rds")

summary_tbl <- results |>
  group_by(sigma_P_level, sigma_P, W_steps) |>
  summarise(across(
    c(sd_pbar, gs_naive, gs_adjusted, mae_naive_all, mae_adjusted_all,
      mae_naive_true_zero, mae_adjusted_true_zero,
      n_phantom_naive_gt_01, n_phantom_adjusted_gt_01),
    list(mean = mean, se = ~ sd(.x) / sqrt(length(.x))),
    .names = "{.col}_{.fn}"
  ), .groups = "drop") |>
  mutate(W_over_tauP = W_steps / tau_P_steps,
         gap_gs = gs_naive_mean - gs_adjusted_mean,
         gap_mae_true_zero = mae_naive_true_zero_mean - mae_adjusted_true_zero_mean)

write.csv(summary_tbl, "res/revision_2026/window_check/window_check_summary.csv", row.names = FALSE)

cat("\n=== SUMMARY (naive vs adjusted, by sigma_P and window length) ===\n")
print(summary_tbl |> select(sigma_P_level, W_steps, W_over_tauP, sd_pbar_mean,
                             gs_naive_mean, gs_adjusted_mean, gap_gs,
                             mae_naive_true_zero_mean, mae_adjusted_true_zero_mean, gap_mae_true_zero))

cat(sprintf("\ntrue global strength = %.2f\n", true_gs))
cat("\nCheck sd_pbar_mean first: if it does not decrease appreciably across\n")
cat("W_steps within a sigma_P level, the window-averaging manipulation isn't\n")
cat("doing anything at that diffusion scale, and gap_gs / gap_mae_true_zero\n")
cat("should not be expected to shrink either -- that would be a genuine,\n")
cat("reportable null result at sigma_P=0.04 (the scale used in Sims 2-3),\n")
cat("not a bug. Compare against the sigma_P=0.65 condition, which should\n")
cat("show a visible sd_pbar decrease if the OU/window mechanics are working.\n")
cat("\nDo NOT reuse the old manuscript's numbers (gap 12.3->10.8->7.7->3.9,\n")
cat("mae 0.132->0.024) -- report whatever gap_gs / gap_mae_true_zero actually\n")
cat("come out as here, even if the shape of the effect differs from the old\n")
cat("(N=12, static-joint-sampler) design.\n")

# ------------------------------------------------------------------------
# Figure: 3-panel summary, one column per sigma_P level, log10(W/tau_P) x-axis
# ------------------------------------------------------------------------
col_raw <- "grey15"
col_adj <- "#1565C0"

theme_pub_local <- function(base_size = 11) {
  theme_classic(base_size = base_size) +
    theme(
      plot.title = element_text(face = "bold", size = base_size),
      axis.title = element_text(size = base_size),
      axis.text = element_text(size = base_size - 1),
      legend.title = element_blank(),
      legend.position = "bottom",
      panel.grid.major.y = element_line(colour = "grey88", linewidth = 0.25),
      panel.grid.major.x = element_blank()
    )
}

x_lab <- expression(W / tau[P] ~ "(observation window / context timescale)")

panelA <- summary_tbl |>
  ggplot(aes(W_over_tauP, sd_pbar_mean, colour = sigma_P_level)) +
  geom_line() + geom_point(size = 2) +
  scale_x_log10() +
  scale_colour_manual(values = c(low = "#2E7D32", high = "#C62828"),
                       labels = c(low = "sigma_P = 0.04 (main-text scale)", high = "sigma_P = 0.65")) +
  labs(x = x_lab, y = expression(SD(bar(P)[W])), title = "(A) Between-person SD of window-averaged context", colour = NULL) +
  theme_pub_local()

panelB <- summary_tbl |>
  select(sigma_P_level, W_over_tauP, gs_naive_mean, gs_adjusted_mean) |>
  pivot_longer(c(gs_naive_mean, gs_adjusted_mean), names_to = "estimator", values_to = "gs") |>
  mutate(estimator = if_else(estimator == "gs_naive_mean", "Symptom-only", "Context-adjusted")) |>
  ggplot(aes(W_over_tauP, gs, colour = estimator, linetype = sigma_P_level)) +
  geom_hline(yintercept = true_gs, colour = "grey50", linetype = "dotted") +
  geom_line() + geom_point(size = 1.8) +
  scale_x_log10() +
  scale_colour_manual(values = c("Symptom-only" = col_raw, "Context-adjusted" = col_adj)) +
  labs(x = x_lab, y = "Estimated global strength", title = "(B) Global strength", colour = NULL, linetype = "sigma_P") +
  theme_pub_local()

panelC <- summary_tbl |>
  select(sigma_P_level, W_over_tauP, mae_naive_true_zero_mean, mae_adjusted_true_zero_mean) |>
  pivot_longer(c(mae_naive_true_zero_mean, mae_adjusted_true_zero_mean), names_to = "estimator", values_to = "mae") |>
  mutate(estimator = if_else(estimator == "mae_naive_true_zero_mean", "Symptom-only", "Context-adjusted")) |>
  ggplot(aes(W_over_tauP, mae, colour = estimator, linetype = sigma_P_level)) +
  geom_line() + geom_point(size = 1.8) +
  scale_x_log10() +
  scale_colour_manual(values = c("Symptom-only" = col_raw, "Context-adjusted" = col_adj)) +
  labs(x = x_lab, y = "Mean |deviation| on truly absent edges", title = "(C) Absent-edge deviation", colour = NULL, linetype = "sigma_P") +
  theme_pub_local()

library(patchwork)
fig_window <- (panelA | panelB | panelC) & theme(legend.position = "bottom")

ggsave("figs/revision_2026/Figure_S_window_check_revised.pdf", fig_window, width = 13.5, height = 4.8)
ggsave("figs/revision_2026/Figure_S_window_check_revised.png", fig_window, width = 13.5, height = 4.8, dpi = 200)

cat("\nDone. Files:\n")
cat("  res/revision_2026/window_check/window_check_raw.rds\n")
cat("  res/revision_2026/window_check/window_check_summary.csv\n")
cat("  figs/revision_2026/Figure_S_window_check_revised.pdf (+ .png)\n")
